# Generated by Django 4.1.1 on 2022-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideshow",
            name="image",
            field=models.FileField(upload_to=None),
        ),
    ]
