# Generated by Django 4.1.1 on 2022-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0002_alter_slideshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideshow",
            name="image",
            field=models.FileField(default=None, upload_to=None),
        ),
    ]
