# Generated by Django 4.1.1 on 2022-10-27 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_rename_prodcuts_products'), ('products', '0003_products_image'), ('products', '0004_products_price_products_quantity')]

    initial = True

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='catagory.catagory')),
                ('image', models.ImageField(default=False, upload_to='product_images/')),
                ('price', models.IntegerField(default=False)),
                ('quantity', models.IntegerField(default=False)),
            ],
        ),
    ]
