# Generated by Django 4.1.1 on 2022-10-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catagory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prodcuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catagory.catagory",
                    ),
                ),
            ],
        ),
    ]
