# Generated by Django 4.1.1 on 2022-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_prodcuts_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(default=False, upload_to="product_images/"),
        ),
    ]
