# Generated by Django 4.1.1 on 2022-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name="products",
            name="quantity",
            field=models.IntegerField(default=False),
        ),
    ]
