# Generated by Django 4.1.1 on 2022-10-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_squashed_0004_products_price_products_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(default="", upload_to="product_images/"),
        ),
    ]
