# Generated by Django 4.1.1 on 2022-11-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.FileField(default=None, upload_to=None),
        ),
    ]
